# Generated by Django 4.0.1 on 2022-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_rename_price_category_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
