# Generated by Django 4.0.1 on 2022-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], default=1, max_length=56),
            preserve_default=False,
        ),
    ]
